// <auto-generated />
namespace XD.Store.Model.Log.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Little1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Little1));
        
        string IMigrationMetadata.Id
        {
            get { return "201909300321270_Little1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
